/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from "react";
import { useGLTF, useVideoTexture } from "@react-three/drei";

const DemoComputer = (props) => {
  const group = useRef();
  const { nodes } = useGLTF("/models/computer.glb");

  const txt = useVideoTexture(
    props.texture ? props.texture : "/textures/project/project1.mp4",
  );

  useEffect(() => {
    if (txt) {
      txt.flipY = false;
    }
  }, [txt]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="monitor-screen"
          geometry={nodes["monitor-screen"].geometry}
          material={nodes["monitor-screen"].material}
          position={[0.127, 1.831, 0.511]}
          rotation={[1.571, -0.005, 0.031]}
          scale={[0.661, 0.608, 0.401]}
        >
          <meshBasicMaterial map={txt} toneMapped={false} />
        </mesh>
      </group>
    </group>
  );
};

useGLTF.preload("/models/computer.glb");

export default DemoComputer;
